/**
 * Domain types for basic board sprint data.
 *
 * These types represent the simplified Step 1 data structure
 * needed for the web UI to render two sprint cards:
 * - "Прошедший спринт" (previous/closed sprint)
 * - "Текущий спринт" (current/active sprint)
 *
 * Also includes version info and alignment analysis.
 */

import type { SprintIssue } from '../ai/types';

// =============================================================================
// Version Metadata
// =============================================================================

/**
 * Version (release) metadata in domain terms.
 * Contains essential version info for display.
 */
export interface VersionMeta {
  id: string;
  name: string;
  description?: string;
  releaseDate?: string;
  released: boolean;
  /** Computed progress percentage (0-100) */
  progressPercent?: number;
}

// =============================================================================
// Sprint Metadata
// =============================================================================

/**
 * Sprint metadata in domain terms (not raw Jira).
 * Contains essential sprint info for display.
 */
export interface SprintMeta {
  id: string;
  name: string;
  state: 'closed' | 'active' | 'future' | string;
  startDate?: string;
  endDate?: string;
  goal?: string;
  /** True if goal was generated by AI (not from Jira) */
  goalIsGenerated?: boolean;
}

// =============================================================================
// Goal Alignment Assessment
// =============================================================================

/**
 * How well the sprint issues match the sprint goal.
 * - strong: Issues clearly support the goal
 * - medium: Some alignment, but not all issues are directly related
 * - weak: Poor alignment between issues and goal
 * - unknown: Cannot assess (no goal or no issues)
 */
export type GoalMatchLevel = 'strong' | 'medium' | 'weak' | 'unknown';

/**
 * Result of goal alignment assessment.
 */
export interface GoalAlignmentResult {
  level: GoalMatchLevel;
  comment: string;
}

// =============================================================================
// Strategic Analysis
// =============================================================================

/**
 * Alignment level for strategic analysis.
 */
export type AlignmentLevel = 'aligned' | 'partial' | 'misaligned' | 'unknown';

/**
 * Analysis of version-sprint goal alignment.
 * Checks if sprint goal contributes to the version goal.
 */
export interface VersionSprintAlignment {
  level: AlignmentLevel;
  comment: string;
  /** Specific recommendations if not aligned */
  recommendations?: string[];
}

/**
 * Analysis of sprint goal vs actual tasks.
 * Checks if completed tasks actually deliver the sprint goal.
 */
export interface SprintTasksAlignment {
  level: AlignmentLevel;
  comment: string;
  /** Percentage of tasks directly related to the goal */
  directlyRelatedPercent?: number;
  /** Tasks that seem unrelated to the sprint goal */
  unrelatedTasks?: string[];
}

/**
 * Demo recommendation for a task.
 */
export interface DemoRecommendation {
  /** Issue key (e.g., "TA-123") */
  issueKey: string;
  /** Issue summary */
  summary: string;
  /** Why this task is good for demo - what WOW effect it creates */
  wowFactor: string;
  /** Estimated complexity for demo (1-5, where 1 is easy) */
  demoComplexity: number;
  /** Suggested demo format */
  suggestedFormat: 'video' | 'screenshot' | 'live' | 'slides';
}

/**
 * Overall strategic analysis for the sprint.
 */
export interface StrategicAnalysis {
  /** Is the sprint goal aligned with the version goal? */
  versionSprintAlignment: VersionSprintAlignment;
  /** Do the tasks actually deliver the sprint goal? */
  sprintTasksAlignment: SprintTasksAlignment;
  /** Overall health score (0-100) */
  overallScore: number;
  /** Summary for partners */
  summary: string;
  /** Recommended tasks for demo with WOW factor */
  demoRecommendations?: DemoRecommendation[];
}

// =============================================================================
// Sprint Card Data
// =============================================================================

/**
 * Complete data for a single sprint card in the UI.
 * Contains sprint metadata, issues, and AI assessments.
 */
export interface SprintCardData {
  /** Sprint metadata (id, name, dates, goal) */
  sprint: SprintMeta;

  /** All issues in this sprint */
  issues: SprintIssue[];

  /** AI-based assessment of how well issues match sprint goal */
  goalMatchLevel: GoalMatchLevel;
  goalMatchComment: string;

  /** Issues suggested for artifacts / demo */
  recommendedArtifactIssues: SprintIssue[];
}

// =============================================================================
// Board Sprint Snapshot
// =============================================================================

/**
 * Availability flags indicating what data was successfully fetched.
 */
export interface BoardDataAvailability {
  hasPreviousSprint: boolean;
  hasCurrentSprint: boolean;
}

/**
 * Complete board sprint snapshot for Step 1.
 *
 * Contains data for two sprints:
 * - previousSprint: Last closed sprint (main sprint for report)
 * - currentSprint: Currently active sprint (if exists)
 *
 * The web UI renders this as two cards.
 */
export interface BasicBoardSprintData {
  /** Board ID that was queried */
  boardId: string;

  /** Project key (e.g., "TA") */
  projectKey?: string;

  /** Project name (e.g., "Toys AI") */
  projectName?: string;

  /** Active version (release) for this board */
  activeVersion?: VersionMeta;

  /** Last closed sprint (main sprint for report) */
  previousSprint?: SprintCardData;

  /** Currently active sprint, if exists */
  currentSprint?: SprintCardData;

  /** Strategic analysis for the current sprint */
  analysis?: StrategicAnalysis;

  /** Flags to indicate what we actually managed to fetch */
  availability: BoardDataAvailability;
}

// =============================================================================
// Re-exports for convenience
// =============================================================================

export type { SprintIssue } from '../ai/types';

