/**
 * Sprint-related types used across CLI and Web.
 */

/**
 * Sprint metadata.
 * Contains essential sprint info for display.
 */
export interface SprintMeta {
  id: string;
  name: string;
  state: 'closed' | 'active' | 'future' | string;
  startDate?: string;
  endDate?: string;
  goal?: string;
  /** True if goal was generated by AI (not from Jira) */
  goalIsGenerated?: boolean;
}

/**
 * Domain type for sprint issues.
 */
export interface SprintIssue {
  key: string;
  summary: string;
  status: string;
  /** 'done' | 'indeterminate' | 'new' */
  statusCategory: string;
  storyPoints: number | null;
  assignee: string | null;
  artifact: string | null;
}

/**
 * How well the sprint issues match the sprint goal.
 */
export type GoalMatchLevel = 'strong' | 'medium' | 'weak' | 'unknown';

/**
 * Complete data for a single sprint card in the UI.
 */
export interface SprintCardData {
  sprint: SprintMeta;
  issues: SprintIssue[];
  goalMatchLevel: GoalMatchLevel;
  goalMatchComment: string;
  recommendedArtifactIssues: SprintIssue[];
}

/**
 * Sprint info used in workflow (simplified view).
 */
export interface SprintInfo {
  id: number | string;
  name: string;
  number: string;
  startDate?: string;
  endDate?: string;
  goal?: string;
}

