/**
 * Sprint-related types used across CLI and Web.
 */

/**
 * Sprint metadata.
 * Contains essential sprint info for display.
 */
export interface SprintMeta {
  id: string;
  name: string;
  state: 'closed' | 'active' | 'future' | string;
  startDate?: string;
  endDate?: string;
  goal?: string;
  /** True if goal was generated by AI (not from Jira) */
  goalIsGenerated?: boolean;
}

/**
 * Domain type for sprint issues.
 */
export interface SprintIssue {
  key: string;
  summary: string;
  status: string;
  /** 'done' | 'indeterminate' | 'new' */
  statusCategory: string;
  storyPoints: number | null;
  assignee: string | null;
  artifact: string | null;
  /** Issue type: История, Задача, Баг, etc. */
  issueType?: string;
  /** Priority: Highest, High, Medium, Low, Lowest */
  priority?: string;
  /** Parent issue key (for subtasks) */
  parentKey?: string;
  /** Epic key this issue belongs to */
  epicKey?: string;
  /** Original estimate in seconds (from Jira timeoriginalestimate field) */
  originalEstimateSeconds?: number | null;
}

/**
 * Epic with its issues in the sprint.
 */
export interface SprintEpic {
  key: string;
  name: string;
  summary: string;
  done: boolean;
  /** Issues from this epic that are in the sprint */
  issues: SprintIssue[];
}

/**
 * Top assignee with task count.
 */
export interface TopAssignee {
  name: string;
  count: number;
}

/**
 * Sprint statistics breakdown.
 */
export interface SprintStatistics {
  /** Count by issue type (История, Задача, Баг) */
  byType: Record<string, number>;
  /** Count by status */
  byStatus: Record<string, number>;
  /** Count by priority */
  byPriority: Record<string, number>;
  /** Top 3 assignees by task count */
  topAssignees: TopAssignee[];
  /** Total issues count */
  totalIssues: number;
}

/**
 * How well the sprint issues match the sprint goal.
 */
export type GoalMatchLevel = 'strong' | 'medium' | 'weak' | 'unknown';

/**
 * Complete data for a single sprint card in the UI.
 */
export interface SprintCardData {
  sprint: SprintMeta;
  issues: SprintIssue[];
  goalMatchLevel: GoalMatchLevel;
  goalMatchComment: string;
  recommendedArtifactIssues: SprintIssue[];
  /** Epics with their issues in this sprint */
  epics?: SprintEpic[];
  /** Statistics breakdown */
  statistics?: SprintStatistics;
}

/**
 * Sprint info used in workflow (simplified view).
 */
export interface SprintInfo {
  id: number | string;
  name: string;
  number: string;
  startDate?: string;
  endDate?: string;
  goal?: string;
}


